java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L1000_4_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L1000_5_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L100_4_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L100_5_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L200_4_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L200_5_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L20_4_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L20_5_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L500_4_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L500_5_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L50_4_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L50_5_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L1000_4_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L1000_5_reg4.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L100_4_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L100_5_reg4.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L200_4_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L200_5_reg4.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L20_4_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L20_5_reg4.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L500_4_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L500_5_reg4.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L50_4_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L50_5_reg4.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L1000_4_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L1000_5_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L100_4_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L100_5_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L200_4_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L200_5_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L20_4_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L20_5_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L500_4_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L500_5_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L50_4_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_1DOF_N1L50_5_reg10.properties