java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_9_Left_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_10_Right_Hip_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_11_Left_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_12_Right_Knee_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_13_Left_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_14_Right_Ankle_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_8_Torso_Omega_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_9_Left_Hip_Omega_test.properties