java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L1000_6_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L1000_7_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L1000_8_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L100_6_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L100_7_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L100_8_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L200_6_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L200_7_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L200_8_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L20_6_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L20_7_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L20_8_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L500_6_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L500_7_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L500_8_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L50_6_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L50_7_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L50_8_reg1.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L1000_6_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L1000_7_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L1000_8_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L100_6_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L100_7_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L100_8_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L200_6_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L200_7_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L200_8_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L20_6_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L20_7_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L20_8_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L500_6_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L500_7_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L500_8_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L50_6_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L50_7_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L50_8_reg2.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L1000_6_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L1000_7_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L1000_8_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L100_6_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L100_7_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L100_8_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L200_6_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L200_7_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L200_8_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L20_6_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L20_7_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L20_8_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L500_6_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L500_7_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L500_8_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L50_6_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L50_7_reg10.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/SNGPConfiguration_syrotek_rw_N1L50_8_reg10.properties