java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_1000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_100_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_2000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_200_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_5000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/10_500_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_1000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_100_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_2000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_200_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_5000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/1_500_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_1000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_100_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_2000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_200_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_5000_7_Right_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_1_Torso_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_2_Left_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_3_Right_Hip_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_4_Left_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_5_Right_Knee_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_6_Left_Ankle_Angle_test.properties
java -jar ../../../Tools/SNGP/SNGP.jar config/5_500_7_Right_Ankle_Angle_test.properties